# Base compose file
#
# Use together with compose.override.yml for development.
# Combine with a custom (e.g. compose.prod.yml) file for production settings.

name: splitzie

services:
  app:
    image: splitzie/app
    environment:
      GS_DB_HOST: db
      GS_DB_USER: postgres
      GS_DB_NAME: postgres
    ports:
      - 8000:8000
    depends_on:
      - db

  static:
    image: splitzie/static
    ports:
      - 8001:80

  media:
    image: nginx:1.25
    ports:
      - 8002:80

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
