# Base compose file
#
# Use together with compose.override.yml for development.
# Combine with a custom (e.g. compose.prod.yml) file for production settings.

name: splitzie

services:
  app:
    image: splitzie/app
    environment:
      GS_DB_HOST: db
      GS_DB_USER: postgres
      GS_DB_NAME: postgres
    depends_on:
      - db

  front:
    # Reverse proxy that sits in front of the app and serves static and media files.
    #
    # Not necessary for development.
    image: splitzie/front
    ports:
      - 8000:80
    depends_on:
      - app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
