# Generated by Django 5.0 on 2023-12-17 01:38

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("splitzie", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "expense", "verbose_name_plural": "expenses"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "group", "verbose_name_plural": "groups"},
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ("name",),
                "verbose_name": "participant",
                "verbose_name_plural": "participants",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
        ),
        migrations.AddField(
            model_name="linkedemail",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("nl", "Dutch")],
                default="en",
                max_length=5,
                verbose_name="language",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entry",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(max_length=150, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="group",
            name="code",
            field=models.CharField(
                default=secrets.token_urlsafe,
                max_length=150,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                default="My group", max_length=150, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="linkedemail",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="name",
            field=models.CharField(max_length=150, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
    ]
